///|
/// Show implementations retained for compatibility with inspect-based tests.

///|
pub impl Show for StickerPlaceholder with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for UniqueGiftColors with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for GiftBackground with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for Gift with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for Gifts with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for AcceptedGiftTypes with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for UniqueGiftInfo with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for StarBalance with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for FilePlaceholder with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for MaskPosition with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for Sticker with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for StickerSet with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for InputSticker with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for GiveawayCreated with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for Giveaway with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for GiveawayWinners with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for GiveawayCompleted with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for PaidMedia with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for PaidMediaPreview with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for PaidMediaPhoto with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for PaidMediaVideo with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for PaidMediaInfo with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for PollOption with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for InputPollOption with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for Poll with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for PollAnswer with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for MessageOriginUser with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for MessageOriginHiddenUser with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for MessageOriginChat with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for MessageOriginChannel with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for MessageOrigin with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for ForumTopic with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for ForumTopicCreated with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for ForumTopicEdited with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for CallbackQuery with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for InlineQuery with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for ChosenInlineResult with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for InlineQueryResultsButton with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for BotCommand with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for WebAppInfo with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for SentWebAppMessage with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for BusinessOpeningHoursInterval with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for BusinessOpeningHours with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for BusinessLocation with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for BusinessIntro with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for BusinessConnection with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for BusinessMessagesDeleted with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for LinkPreviewOptions with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for TextQuote with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for MessageId with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for CachedInputMessageContent with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for InlineQueryResultCachedPhoto with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for InlineQueryResultCachedGif with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for InlineQueryResultCachedMpeg4Gif with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for InlineQueryResultCachedSticker with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for InlineQueryResultCachedDocument with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for InlineQueryResultCachedVideo with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for InlineQueryResultCachedVoice with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for InlineQueryResultCachedAudio with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for InlineKeyboardButton with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for InlineKeyboardMarkup with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for Audio with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for Voice with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for ChatId with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for ReplyParameters with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for MessageOriginPlaceholder with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for LinkPreviewPlaceholder with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for GamePlaceholder with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for ExternalReplyInfo with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for ForumTopicClosed with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for ForumTopicReopened with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for GeneralForumTopicHidden with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for GeneralForumTopicUnhidden with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for VideoChatStarted with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for VideoChatEnded with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for VideoChatScheduled with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for VideoChatParticipantsInvited with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for MessageAutoDeleteTimerChanged with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for ChatBoostAdded with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for ProximityAlertTriggered with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for WriteAccessAllowed with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for WebAppData with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for InputTextMessageContent with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for InputLocationMessageContent with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for InputVenueMessageContent with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for InputContactMessageContent with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for InputInvoiceMessageContent with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for InputMessageContent with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for KeyboardButtonPollType with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for KeyboardButtonRequestUsers with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for KeyboardButtonRequestChat with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for KeyboardButton with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for SharedUser with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for UsersShared with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for ChatShared with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for File with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for Story with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for Birthdate with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for ChatLocation with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for ReactionTypeEmoji with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for ReactionTypeCustomEmoji with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for ReactionType with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for ChatFullInfo with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for ChecklistTask with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for Checklist with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for InputChecklistTask with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for InputChecklist with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for ChecklistTasksDone with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for ChecklistTasksAdded with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for BotCommandScopeChat with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for BotCommandScopeChatAdministrators with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for BotCommandScopeChatMember with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for BotCommandScope with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for InlineQueryResultArticle with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for InlineQueryResultContact with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for InlineQueryResultLocation with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for InlineQueryResultVenue with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for MessageEntity with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for Message with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for User with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for Video with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for Update with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for ChatPhoto with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for Venue with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for PassportElementErrorDataField with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for PassportElementErrorFrontSide with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for PassportElementErrorReverseSide with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for PassportElementErrorSelfie with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for PassportElementErrorFile with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for PassportElementErrorFiles with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for PassportElementErrorTranslationFile with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for PassportElementErrorTranslationFiles with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for PassportElementErrorUnspecified with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for PassportElementError with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for InputMessageContentPlaceholder with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for InlineQueryResultAudio with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for InlineQueryResultVoice with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for InlineQueryResultDocument with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for ChatType with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for Chat with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for SuggestedPostParameters with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for SuggestedPostInfo with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for SuggestedPostPrice with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for SuggestedPostApproved with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for SuggestedPostDeclined with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for SuggestedPostPaid with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for SuggestedPostApprovalFailed with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for PassportFile with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for EncryptedCredentials with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for EncryptedPassportElement with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for PassportData with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for Dice with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for PhotoSize with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for LoginUrl with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for SwitchInlineQueryChosenChat with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for CallbackGame with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for GiftInfo with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for WebhookInfo with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for ChatMemberOwner with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for ChatMemberAdministrator with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for ChatMemberMember with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for ChatMemberRestricted with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for ChatMemberLeft with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for ChatMemberBanned with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for ChatMember with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for ChatPermissions with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for ChatAdministratorRights with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for DocumentPlaceholder with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for BackgroundFillSolid with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for BackgroundFillGradient with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for BackgroundFillFreeformGradient with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for BackgroundFill with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for BackgroundTypeFill with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for BackgroundTypeWallpaper with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for BackgroundTypePattern with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for BackgroundTypeChatTheme with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for BackgroundType with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for ChatBackground with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for DirectMessagesTopic with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for Location with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for ReplyKeyboardMarkup with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for ReplyKeyboardRemove with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for ForceReply with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for VideoNote with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for Contact with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for Invoice with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for LabeledPrice with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for ShippingAddress with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for OrderInfo with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for ShippingOption with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for SuccessfulPayment with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for RefundedPayment with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for Animation with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for Document with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for InlineQueryResultPhoto with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for InlineQueryResultGif with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for InlineQueryResultMpeg4Gif with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}

///|
pub impl Show for InlineQueryResultVideo with output(self, logger) {
  logger.write_string(@debug.to_string(self))
}
